%YAML:1.0

#--------------------------------------------------------------------------------------------
# System config
#--------------------------------------------------------------------------------------------

# When the variables are commented, the system doesn't load a previous session or not store the current one

# If the LoadFile doesn't exist, the system give a message and create a new Atlas from scratch
#System.LoadAtlasFromFile: "Session_MH01_MH02_MH03_Stereo60_Pseudo"

# The store file is created from the current session, if a file with the same name exists it is deleted
#System.SaveAtlasToFile: "Session_MH01_MH02_MH03_Stereo60_Pseudo"

#--------------------------------------------------------------------------------------------
# Camera Parameters. Adjust them!
#--------------------------------------------------------------------------------------------
File.version: "1.0"

Camera.type: "PinHole"

# Camera calibration and distortion parameters (OpenCV) 
Camera1.fx: 263.80438232421875
Camera1.fy: 263.80438232421875
Camera1.cx: 316.25775146484375
Camera1.cy: 176.42626953125

Camera1.k1: 0.0
Camera1.k2: 0.0
Camera1.p1: 0.0
Camera1.p2: 0.0

Camera2.fx: 263.80438232421875
Camera2.fy: 263.80438232421875
Camera2.cx: 316.25775146484375
Camera2.cy: 176.42626953125

Camera2.k1: 0.0
Camera2.k2: 0.0
Camera2.p1: 0.0
Camera2.p2: 0.0

Camera.width: 640
Camera.height: 360

# Camera frames per second 
Camera.fps: 15

# Color order of the images (0: BGR, 1: RGB. It is ignored if images are grayscale)
Camera.RGB: 1

# Close/Far threshold. Baseline times.
Stereo.ThDepth: 60.0
# c1 = left, c2 = right
Stereo.T_c1_c2: !!opencv-matrix
  rows: 4
  cols: 4
  dt: f
  data: [1.0, 0.0, 0.0, -0.120,
         0.0, 1.0, 0.0, 0.0,
         0.0, 0.0, 1.0, 0.0,
         0.0, 0.0, 0.0, 1.0]

# Transformation from camera 0 to body-frame (imu)
IMU.T_b_c1: !!opencv-matrix
  rows: 4
  cols: 4
  dt: f
  # data: [0.999997, -0.002629, -0.000225 ,-0.002000,
  #        0.002628, 0.999991, -0.003261, -0.023000,
  #        0.000234, 0.003261, 0.999995, 0.000220,
  #        0.000000, 0.000000, 0.000000, 1.000000]
  data: [-0.0030000, -0.9999910,  0.0030030,0.023000,
         -0.0010050, -0.0030000, -0.9999950, 0.0,
         0.9999950, -0.0030030, -0.0009960, 0.0020,
         0.000000, 0.000000, 0.000000, 1.000000]
  # data: [0.99999603828738987114, 0.0026282515638749065113,0.00023357100481948288857,0.0020603904769228423058,
  #       -0.0026287483675788706382,0.99999145678911989869,0.0032603969741914857015,0.022993828722080277802,
  #       -0.00022542785167183289187,-0.0032616034594725640807,0.99999431316141784097,-0.00029546648416672456464,
  #        0,0,0,1]


# IMU noise
IMU.NoiseGyro: 0.007000000216066837
IMU.NoiseAcc:  0.0015999999595806003
IMU.GyroWalk: 0.0019474000437185168
IMU.AccWalk: 0.0002508999896235764
IMU.Frequency: 400.0

#--------------------------------------------------------------------------------------------
# ORB Parameters
#--------------------------------------------------------------------------------------------

# ORB Extractor: Number of features per image
ORBextractor.nFeatures: 1200

# ORB Extractor: Scale factor between levels in the scale pyramid 	
ORBextractor.scaleFactor: 1.2

# ORB Extractor: Number of levels in the scale pyramid	
ORBextractor.nLevels: 8

# ORB Extractor: Fast threshold
# Image is divided in a grid. At each cell FAST are extracted imposing a minimum response.
# Firstly we impose iniThFAST. If no corners are detected we impose a lower value minThFAST
# You can lower these values if your images have low contrast			
ORBextractor.iniThFAST: 20
ORBextractor.minThFAST: 7

#--------------------------------------------------------------------------------------------
# Viewer Parameters
#--------------------------------------------------------------------------------------------
Viewer.KeyFrameSize: 0.05
Viewer.KeyFrameLineWidth: 1.0
Viewer.GraphLineWidth: 0.9
Viewer.PointSize: 2.0
Viewer.CameraSize: 0.08
Viewer.CameraLineWidth: 3.0
Viewer.ViewpointX: 0.0
Viewer.ViewpointY: -0.7
Viewer.ViewpointZ: -1.8
Viewer.ViewpointF: 500.0
Viewer.imageViewScale: 1.0
